config/routes.rb
Rails.application.routes.draw do
  root 'say#hello'
  get 'say/hello'
  get 'say/goodbye'
  get 'say/filenames'
  get 'say/filesearch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
    before_action :time_now

    def hello
    end

    def goodbye
    end

    def filenames
        @files = Dir.glob('*')
    end
    
    def filesearch
    query = params[:query]
    files = Dir.glob('*').select {|s| s.include? "#{query}"}

    render json: files
    end
    
    private

    def time_now
        @time = Time.now
    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/filenames.html.erb
<div class="container">
    <div class="card">
      <div class="card-header">
        It is now <%=@time%>
      </div>
      <div class="card-body">
        <h5 class="card-title">File Names</h5>

        <%= content_tag :div,
            id: "files",
            data: @files.to_json do %>

            <%= javascript_pack_tag 'files' %>

        <% end %>

        <p>
          Say <%= link_to "Hello", say_hello_path %> again.
        </p>
      </div>
    </div>
</div>
<!--
Addition: <%= 1+2 %>
Concatenation: <%= "cow" + "boy" %>
Time in one hour: <%= 1.hour.from_now.localtime %>
-->

app/views/say/goodbye.html.erb
<div class="container">
    <div class="card">
      <div class="card-header">
        It is now <%=@time%>
      </div>
      <div class="card-body">
        <h5 class="card-title">It was nice having you here.</h5>

         <p>
                Say 
                <%=link_to "Hello", say_hello_path %> again.
         </p>
      </div>
    </div>
</div>

app/views/say/hello.html.erb
<div class="container">
    <div class="card">
      <div class="card-header">
        It is now <%=@time%>
      </div>
      <div class="card-body">
        <h5 class="card-title">Hello World from Sean Passmore</h5>
         <p>
                List of 
                <%=link_to "File Names", say_filenames_path %>!
         </p>
         <p>
                Time to say 
                <%=link_to "Goodbye", say_goodbye_path %>!
         </p>
      </div>
    </div>
</div>